# Generated by Django 2.0.5 on 2018-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the API that is assigned to this key pair', max_length=100, verbose_name='Name of the assigned API')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
            ],
            options={
                'verbose_name': 'key_pair',
                'verbose_name_plural': 'key_pairs',
            },
        ),
    ]
